### ISSUE TITLE
[BUG] RAM shows upon joining

### ISSUE THREAD

**Issue by yorik100** [LoneDev6/IAServerMonitor#3]
When connecting, you always see the RAM

![image](https://github.com/LoneDev6/API-ItemsAdder-Example-ServerMonitor/assets/16320315/ce05cd28-05fb-4eec-8a68-bbcfc3497e7a)

Everytime you join, you have to /monitor ram twice to remove the RAM indicator
Another issue is that /monitor causes errors
These issues also happen on the test server

Issue found and is from ItemsAdder,
```yml
#hud_ram.yml
    enabled: true
    show:
      auto: false
    type: FRAMES
```
Seems like "FRAMES" ignores auto being false
